[template]
cargo_generate_version = ">=0.10.0"
exclude = [
    "justfile"
]

[placeholders.project-description]
type = "string"
prompt = "Project description?"

[placeholders.project-url]
type = "string"
prompt = "Project url?"

[hooks]
pre = [
    "fix-readme.rhai",
    "ask-license.rhai",
    "ask-crate-type.rhai",
]