# requires unstable rustfmt until the options are stabilized (https://github.com/rust-lang/rustfmt/blob/master/Configurations.md)
indent_style = "Block"
reorder_imports = true
format_code_in_doc_comments = false
imports_layout = "HorizontalVertical"
imports_granularity="Crate"
#array_width=100 # unreleased 2.0
#binop_operator="Front" # unreleased 2.0
blank_lines_lower_bound=0
blank_lines_upper_bound=2
brace_style="SameLineWhere"
edition="2021"
empty_item_single_line=true
match_block_trailing_comma=true
struct_field_align_threshold=20
use_field_init_shorthand=true
wrap_comments=true
condense_wildcard_suffixes=true
force_explicit_abi=true
format_macro_matchers=false
format_macro_bodies=false
format_strings=true
chain_width=90
group_imports = "StdExternalCrate"
